// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannel(arg1) {
  return window['go']['main']['GuiApp']['AddChannel'](arg1);
}

export function AddCron(arg1) {
  return window['go']['main']['GuiApp']['AddCron'](arg1);
}

export function AddSkill(arg1) {
  return window['go']['main']['GuiApp']['AddSkill'](arg1);
}

export function CancelCurrentTask() {
  return window['go']['main']['GuiApp']['CancelCurrentTask']();
}

export function CreateTask(arg1) {
  return window['go']['main']['GuiApp']['CreateTask'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['GuiApp']['DeleteChannel'](arg1);
}

export function DeleteCron(arg1) {
  return window['go']['main']['GuiApp']['DeleteCron'](arg1);
}

export function GetChannels() {
  return window['go']['main']['GuiApp']['GetChannels']();
}

export function GetConfig() {
  return window['go']['main']['GuiApp']['GetConfig']();
}

export function GetCrons() {
  return window['go']['main']['GuiApp']['GetCrons']();
}

export function GetSkills() {
  return window['go']['main']['GuiApp']['GetSkills']();
}

export function GetTaskDetail(arg1) {
  return window['go']['main']['GuiApp']['GetTaskDetail'](arg1);
}

export function GetTasks() {
  return window['go']['main']['GuiApp']['GetTasks']();
}

export function GetTodos() {
  return window['go']['main']['GuiApp']['GetTodos']();
}

export function GetWorkingFiles() {
  return window['go']['main']['GuiApp']['GetWorkingFiles']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['GuiApp']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetConfig(arg1) {
  return window['go']['main']['GuiApp']['SetConfig'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['GuiApp']['SetWorkDir'](arg1);
}

export function ToggleChannel(arg1) {
  return window['go']['main']['GuiApp']['ToggleChannel'](arg1);
}

export function ToggleCron(arg1) {
  return window['go']['main']['GuiApp']['ToggleCron'](arg1);
}

export function ToggleSkill(arg1) {
  return window['go']['main']['GuiApp']['ToggleSkill'](arg1);
}
