// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddChannel(arg1:main.ChannelInput):Promise<string>;

export function AddCron(arg1:main.CronInput):Promise<string>;

export function AddSkill(arg1:main.SkillInput):Promise<string>;

export function CancelCurrentTask():Promise<string>;

export function CreateTask(arg1:string):Promise<main.Task>;

export function DeleteChannel(arg1:number):Promise<string>;

export function DeleteCron(arg1:number):Promise<string>;

export function GetChannels():Promise<Array<main.Channel>>;

export function GetConfig():Promise<main.Config>;

export function GetCrons():Promise<Array<main.CronJob>>;

export function GetSkills():Promise<Array<main.Skill>>;

export function GetTaskDetail(arg1:number):Promise<main.Task>;

export function GetTasks():Promise<Array<main.Task>>;

export function GetTodos():Promise<Array<main.TodoItem>>;

export function GetWorkingFiles():Promise<Array<main.FileInfo>>;

export function SendMessage(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function SetConfig(arg1:main.Config):Promise<string>;

export function SetWorkDir(arg1:string):Promise<string>;

export function ToggleChannel(arg1:number):Promise<string>;

export function ToggleCron(arg1:number):Promise<string>;

export function ToggleSkill(arg1:number):Promise<string>;
